development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:536195394c396e7577823c01323a4db7@soapfish.redistogo.com:11294/

  channel_prefix: rails-redux-chat_production
